### ISSUE TITLE
Add unit test example with Karma

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular2-seed#101]

**Comment by gdi2290** [comment]
karma adds a ton of deps and install time :/

**Comment by pkozlowski-opensource** [comment]
> karma adds a ton of deps and install time

Not surprised. I think at some point there was an effort to clean those up. In any case if we think that Karma is "too heavy" we should take it with the Karma project.

**Comment by gdi2290** [comment]
a lot of people who complain about bloat in angular2-webpack-starter, when asked, really just say it's due to tests, e2e, docs, and introducing prod/dev/test with karma being the largest contributor to install size. Installing angular2-webpack-starter also takes forever initially due to the same features that people consider as bloat but later they want them. I see this repo being more focused on quick Angular 2 development/prototyping

**Comment by caraya** [comment]
if someone develops an app with this project do you have a path to move them to a heavier, full featured development ecosystem that has all the things people complaint about and then decide they want? Is the build system commented in such a way that someone relatively new to Angular 2 can figure out what to do to activate the features?

**Comment by RickStrahl** [comment]
Git is really not a good delivery mechanism for a 'template' precisely because you can't really customize things. :-)

I for one appreciate the 'just what you need' approach of this template - it's been my go to to get started and share with other devs. You can always add later.

Ultimately though a better solution is needed that allows choosing the features you want and more importantly lets you add features later (that's the really tough part). With the CLI up in the air this is a problem that really needs addressing IMHO.

**Comment by gdi2290** [comment]
I think you're describing the CLI for choosing if you want tests or not. this starter won't have tests as karma adds a ton of bloat. If someone wants tests they can use the CLI or every other starter. This starter is only meant for quick setup/prototyping/quick development
